#!/bin/sh
#---------------------------------------------------------------
# Project         : logilic
# File            : logilic_compile
# Copyright       : (C) 2012 Frederic Lepied
# Author          : Pablo Duboue
# Created On      : Mon Dec  3 02:53:36 EST 2012
# Purpose         : compile the project using GNU Prolog or
#                   SWI prolog with the right options.
#---------------------------------------------------------------

base="`dirname $0`"
dir="`cd $base; pwd`"

if [ ! -r "$1" ]; then
    echo "Usage: $0 <project file>" 1>&2
    exit 1
fi

basenameproject="`basename $1 .pl`"
dirnameproject="`dirname $1`"

if type gplc > /dev/null 2>&1; then
    gplc -o "$dirnameproject"/"logilic_$basenameproject" "$dir"/predicates.pl "$dir"/licenses.pl "$1"
elif type swipl > /dev/null 2>&1; then
    swipl -o "$dirnameproject"/"logilic_$basenameproject" -c "$dir"/predicates.pl "$dir"/licenses.pl "$1"
else
    echo "No prolog compiler found. Install GNU Prolog or SWI-Prolog." 1>&2
    exit 1
fi

# logilic_compile ends here
