#!/bin/sh
#---------------------------------------------------------------
# Project         : logilic
# File            : logilic
# Copyright       : (C) 2012 Frederic Lepied
# Author          : Frederic Lepied
# Created On      : Sat Dec  1 11:11:09 2012
# Purpose         : launch gprolog with the right options
#---------------------------------------------------------------

base="`dirname $0`"
dir="`cd $base; pwd`"

if [ ! -r "$1" ]; then
    echo "Usage: $0 <project file>" 1>&2
    exit 1
fi

gprolog --consult-file "$dir"/predicates.pl --consult-file "$dir"/licenses.pl --consult-file "$1"

# logilic ends here
