#!/bin/sh
#---------------------------------------------------------------
# Project         : logilic
# File            : logilic_compile
# Copyright       : (C) 2012 Frederic Lepied
# Author          : Pablo Duboue
# Created On      : Mon Dec  3 02:53:36 EST 2012
# Purpose         : compile the project using GNU Prolog or
#                   SWI prolog with the right options.
#---------------------------------------------------------------

base="`dirname $0`"
dir="`cd $base; pwd`"

if [ ! -r "$1" ]; then
    echo "Usage: $0 <project file>" 1>&2
    exit 1
fi

basenameproject="`basename $1 .pl`"
dirnameproject="`dirname $1`"

if [ -n "$PROLOG_COMPILER" ] && type "$PROLOG_COMPILER" > /dev/null 2>&1; then
    :
elif type gplc > /dev/null 2>&1; then
    PROLOG_COMPILER=gplc
    PROLOG_COMPILER_OPTS=
elif type swipl > /dev/null 2>&1; then
    PROLOG_COMPILER=swipl
    PROLOG_COMPILER_OPTS=-c
else
    echo "No prolog compiler found. Install GNU Prolog or SWI-Prolog." 1>&2
    exit 1
fi

"$PROLOG_COMPILER" -o "$dirnameproject"/"logilic_$basenameproject" $PROLOG_COMPILER_OPTS "$dir"/predicates.pl "$dir"/licenses.pl "$1"

# logilic_compile ends here
